paths:
  /hook:
    post:
      operationId: updateMMF
      summary: 백서/문서 자동 갱신
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: OK
