name: Whitepaper Auto-Update

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/MMF_Ellys_MVF_Whitepaper.md'
      - 'scripts/generate_mmf_whitepaper.py'

jobs:
  update-whitepaper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 백서 자동생성
        run: python scripts/generate_mmf_whitepaper.py
      - name: 커밋 & 푸시
        run: |
          git config --global user.name "sentinel-bot"
          git config --global user.email "sentinel@bot.com"
          git add docs/MMF_Ellys_MVF_Whitepaper.md
          git commit -m "백서 자동 업데이트" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/kuroru/MMF-Core-Ellys.git HEAD:main
