name: Release After PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: 최신 백서 파일 확인
        run: cat docs/MMF_Ellys_MVF_Whitepaper.md | head -20

      - name: 릴리즈 생성 및 파일 첨부
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ github.run_number }}
          name: "MMF 백서 PR 머지 릴리즈 ${{ github.run_number }}"
          body: |
            이 릴리즈는 PR 머지 후 자동으로 생성되었습니다.
            - 버전: ${{ github.run_number }}
            - 파일: docs/MMF_Ellys_MVF_Whitepaper.md
          files: docs/MMF_Ellys_MVF_Whitepaper.md
