name: Whitepaper Release Auto-Trigger

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'docs/MMF_Ellys_MVF_Whitepaper.md'

jobs:
  release-whitepaper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 최신 백서 파일 확인
        run: cat docs/MMF_Ellys_MVF_Whitepaper.md | head -20

      - name: 릴리즈 생성 및 파일 첨부
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ github.run_number }}
          name: "MMF Whitepaper Release ${{ github.run_number }}"
          body: |
            MMF 백서 자동 릴리즈입니다.
            - 버전: ${{ github.run_number }}
            - 파일: docs/MMF_Ellys_MVF_Whitepaper.md
          files: docs/MMF_Ellys_MVF_Whitepaper.md
